export default {
    playstyle:[
        {playId: 0, playName:"Beginner", blank:""},
        {playId: 1, playName:"Casual", blank:""},
        {playId: 2, playName:"Competitive", blank:""},
        {playId: 3, playName:"Experimental", blank:""}
    ],
    characters:[
        {charId:0, charName: "Bayonetta", thumbnail:""},
        {charId:1, charName: "Bowser", thumbnail:""},
        {charId:2, charName: "Bowser Jr.", thumbnail:""},
        {charId:3, charName: "Captain Falcon", thumbnail:""},
        {charId:4, charName: "Charizard", thumbnail:""},
        {charId:5, charName: "Cloud", thumbnail:""},
        {charId:6, charName: "Corrin", thumbnail:""},
        {charId:7, charName: "Daisy", thumbnail:""},
        {charId:8, charName: "Dark Pit", thumbnail:""},
        {charId:9, charName: "Diddy Kong", thumbnail:""},
        {charId:10, charName: "Donkey Kong", thumbnail:""},
        {charId:11, charName: "Dr. Mario", thumbnail:""},
        {charId:12, charName: "Duck Hunt", thumbnail:""},
        {charId:13, charName: "Falco", thumbnail:""},
        {charId:14, charName: "Fox", thumbnail:""},
        {charId:15, charName: "Ganondorf", thumbnail:""},
        {charId:16, charName: "Greninja", thumbnail:""},
        {charId:17, charName: "Ice Climbers", thumbnail:""},
        {charId:18, charName: "Ike", thumbnail:""},
        {charId:19, charName: "Inkling", thumbnail:""},
        {charId:20, charName: "Ivysaur", thumbnail:""},
        {charId:21, charName: "Jigglypuff", thumbnail:""},
        {charId:22, charName: "King Dedede", thumbnail:""},
        {charId:23, charName: "Kirby", thumbnail:""},
        {charId:24, charName: "Link", thumbnail:""},
        {charId:25, charName: "Little Mac", thumbnail:""},
        {charId:26, charName: "Lucario", thumbnail:""},
        {charId:27, charName: "Lucas", thumbnail:""},
        {charId:28, charName: "Lucina", thumbnail:""},
        {charId:29, charName: "Luigi", thumbnail:""},
        {charId:30, charName: "Mario", thumbnail:""},
        {charId:31, charName: "Marth", thumbnail:""},
        {charId:32, charName: "Mega Man", thumbnail:""},
        {charId:33, charName: "Meta Knight", thumbnail:""},
        {charId:34, charName: "Mewtwo", thumbnail:""},
        {charId:35, charName: "Mii Brawler", thumbnail:""},
        {charId:36, charName: "Mii Gunner", thumbnail:""},
        {charId:37, charName: "Mii Swordfighter", thumbnail:""},
        {charId:38, charName: "Mr. Game & Watch", thumbnail:""},
        {charId:39,charName: "Ness", thumbnail:""},
        {charId:40, charName: "Olimar", thumbnail:""},
        {charId:41, charName: "Pac-Man", thumbnail:""},
        {charId:42, charName: "Palutena", thumbnail:""},
        {charId:43, charName: "Peach", thumbnail:""},
        {charId:44, charName: "Pichu", thumbnail:""},
        {charId:45, charName: "Pikachu", thumbnail:""},
        {charId:46, charName: "Pit", thumbnail:""},
        {charId:47, charName: "Pokémon Trainer", thumbnail:""},
        {charId:48, charName: "R.O.B.", thumbnail:""},
        {charId:49, charName: "Ridley", thumbnail:""},
        {charId:50, charName: "Robin", thumbnail:""},
        {charId:51, charName: "Rosalina", thumbnail:""},
        {charId:52, charName: "Roy", thumbnail:""},
        {charId:53, charName: "Ryu", thumbnail:""},
        {charId:54, charName: "Samus", thumbnail:""},
        {charId:55, charName: "Sheik", thumbnail:""},
        {charId:56, charName: "Shulk", thumbnail:""},
        {charId:57, charName: "Snake", thumbnail:""},
        {charId:58, charName: "Sonic", thumbnail:""},
        {charId:59, charName: "Squirtle", thumbnail:""},
        {charId:60, charName: "Toon Link", thumbnail:""},
        {charId:61, charName: "Villager", thumbnail:""},
        {charId:62, charName: "Wario", thumbnail:""},
        {charId:63, charName: "Wii Fit Trainer", thumbnail:""},
        {charId:64, charName: "Wolf", thumbnail:""},
        {charId:65, charName: "Yoshi", thumbnail:""},
        {charId:66, charName: "Young Link", thumbnail:""},
        {charId:67, charName: "Zelda", thumbnail:""},
        {charId:68, charName: "Zero Suit Samus", thumbnail:""},

        
    ],

    radius:[
        {value: 0, label: "10 Miles"},
        {value: 1, label: "20 Miles"},
        {value: 2, label: "30 Miles"},
        {value: 3, label: "40 Miles"},
        {value: 4, label: "50 Miles"},
    ],

    

    
}