export default {
    playstyle:[
        {playId: 1, playName:"Beginner", blank:""},
        {playId: 2, playName:"Casual", blank:""},
        {playId: 3, playName:"Competitive", blank:""},
        {playId: 4, playName:"Experimental", blank:""}
    ],
    characters:[
        {charId:1, charName: "Bayonetta", thumbnail:"bayonetta.png"},
        {charId:2, charName: "Bowser", thumbnail:"bowser.png"},
        {charId:3, charName: "Bowser Jr.", thumbnail:"bowser_jr.png"},
        {charId:4, charName: "Captain Falcon", thumbnail:"captain_falcon.png"},
        {charId:5, charName: "Charizard", thumbnail:"pokemon_trainer.png"},
        {charId:6, charName: "Cloud", thumbnail:"cloud.png"},
        {charId:7, charName: "Corrin", thumbnail:"corrin.png"},
        {charId:8, charName: "Daisy", thumbnail:"daisy.png"},
        {charId:9, charName: "Dark Pit", thumbnail:"dark_pit.png"},
        {charId:10, charName: "Diddy Kong", thumbnail:"diddy_kong.png"},
        {charId:11, charName: "Donkey Kong", thumbnail:"donkey_kong.png"},
        {charId:12, charName: "Dr. Mario", thumbnail:"dr_mario.png"},
        {charId:13, charName: "Duck Hunt", thumbnail:"duck_hunt.png"},
        {charId:14, charName: "Falco", thumbnail:"falco.png"},
        {charId:15, charName: "Fox", thumbnail:"fox.png"},
        {charId:16, charName: "Ganondorf", thumbnail:"ganondorf.png"},
        {charId:17, charName: "Greninja", thumbnail:"greninja.png"},
        {charId:18, charName: "Ice Climbers", thumbnail:"ice_climbers.png"},
        {charId:19, charName: "Ike", thumbnail:"ike.png"},
        {charId:20, charName: "Inkling", thumbnail:"inkling.png"},
        {charId:21, charName: "Ivysaur", thumbnail:"pokemon_trainer.png"},
        {charId:22, charName: "Jigglypuff", thumbnail:"jigglypuff.png"},
        {charId:23, charName: "King Dedede", thumbnail:"king_dedede.png"},
        {charId:24, charName: "Kirby", thumbnail:"kirby.png"},
        {charId:25, charName: "Link", thumbnail:"link.png"},
        {charId:26, charName: "Little Mac", thumbnail:"little_mac.png"},
        {charId:27, charName: "Lucario", thumbnail:"lucario.png"},
        {charId:28, charName: "Lucas", thumbnail:"lucas.png"},
        {charId:29, charName: "Lucina", thumbnail:"lucina.png"},
        {charId:30, charName: "Luigi", thumbnail:"luigi.png"},
        {charId:31, charName: "Mario", thumbnail:"mario.png"},
        {charId:32, charName: "Marth", thumbnail:"marth.png"},
        {charId:33, charName: "Mega Man", thumbnail:"mega_man.png"},
        {charId:34, charName: "Meta Knight", thumbnail:"meta_knight.png"},
        {charId:35, charName: "Mewtwo", thumbnail:"mewtwo.png"},
        {charId:36, charName: "Mii Brawler", thumbnail:"mii_fighter.png"},
        {charId:37, charName: "Mii Gunner", thumbnail:"mii_fighter.png"},
        {charId:38, charName: "Mii Swordfighter", thumbnail:"mii_fighter.png"},
        {charId:39, charName: "Mr. Game & Watch", thumbnail:"mr_game_and_watch.png"},
        {charId:40, charName: "Ness", thumbnail:"ness.png"},
        {charId:41, charName: "Olimar", thumbnail:"olimar.png"},
        {charId:42, charName: "Pac-Man", thumbnail:"pac_man.png"},
        {charId:43, charName: "Palutena", thumbnail:"palutena.png"},
        {charId:44, charName: "Peach", thumbnail:"peach.png"},
        {charId:45, charName: "Pichu", thumbnail:"pichu.png"},
        {charId:46, charName: "Pikachu", thumbnail:"pikachu.png"},
        {charId:47, charName: "Pit", thumbnail:"pit.png"},
        {charId:48, charName: "Pokémon Trainer", thumbnail:"pokemon_trainer.png"},
        {charId:49, charName: "R.O.B.", thumbnail:"rob.png"},
        {charId:50, charName: "Ridley", thumbnail:"ridley.png"},
        {charId:51, charName: "Robin", thumbnail:"robin.png"},
        {charId:52, charName: "Rosalina", thumbnail:"rosalina_and_luma.png"},
        {charId:53, charName: "Roy", thumbnail:"roy.png"},
        {charId:54, charName: "Ryu", thumbnail:"ryu.png"},
        {charId:55, charName: "Samus", thumbnail:"samus.png"},
        {charId:56, charName: "Sheik", thumbnail:"sheik.png"},
        {charId:57, charName: "Shulk", thumbnail:"shulk.png"},
        {charId:58, charName: "Snake", thumbnail:"snake.png"},
        {charId:59, charName: "Sonic", thumbnail:"sonic.png"},
        {charId:60, charName: "Squirtle", thumbnail:"pokemon_trainer.png"},
        {charId:61, charName: "Toon Link", thumbnail:"toon_link.png"},
        {charId:62, charName: "Villager", thumbnail:"villager.png"},
        {charId:63, charName: "Wario", thumbnail:"wario.png"},
        {charId:64, charName: "Wii Fit Trainer", thumbnail:"wii_fit_trainer.png"},
        {charId:65, charName: "Wolf", thumbnail:"wolf.png"},
        {charId:66, charName: "Yoshi", thumbnail:"yoshi.png"},
        {charId:67, charName: "Young Link", thumbnail:"young_link.png"},
        {charId:68, charName: "Zelda", thumbnail:"zelda.png"},
        {charId:69, charName: "Zero Suit Samus", thumbnail:"zero_suit_samus.png"},
        {charId:70, charName: "Ken", thumbnail:"ken.png"},
        {charId:71, charName: "Simon", thumbnail:"simon.png"},
        {charId:72, charName: "Richter", thumbnail:"richter.png"},
        {charId:73, charName: "King K. Rool", thumbnail:"king_k_rool.png"},
        {charId:74, charName: "Isabelle", thumbnail:"shizue.png"},
        {charId:75, charName: "Incineroar", thumbnail:"zero_suit_samus.png"},
        {charId:76, charName: "Pirahna Plant", thumbnail:"packun_flower.png"},

        
    ],

    radius:[
        {radiusVal: 16093.4, text: "10 Miles"},
        {radiusVal: 32186.8, text: "20 Miles"},
        {radiusVal: 48280.2, text: "30 Miles"},
        {radiusVal: 64373.6, text: "40 Miles"},
        {radiusVal: 80467, text: "50 Miles"},
    ],
    

    
}